### ISSUE TITLE
Cannot create username with v3.14.1

### ISSUE THREAD

**Issue by readme55** [dashevo/DashJS#119]
## Current Behavior

When i run the tutorial code for registering username (without specifying dpns contractid in clientOpts) i get this error with 3.14.1 release:

```
Something went wrong: Error: 3 INVALID_ARGUMENT: Invalid state transition
    at Object.exports.createStatusError (C:\Users\rm\myProjects\Projects\evonet\node_modules\dash\node_modules\grpc\src\common.js:91:15)
    at Object.onReceiveStatus (C:\Users\rm\myProjects\Projects\evonet\node_modules\dash\node_modules\grpc\src\client_interceptors.js:1209:28)
    at InterceptingListener._callNext (C:\Users\rm\myProjects\Projects\evonet\node_modules\dash\node_modules\grpc\src\client_interceptors.js:568:42)
    at InterceptingListener.onReceiveStatus (C:\Users\rm\myProjects\Projects\evonet\node_modules\dash\node_modules\grpc\src\client_interceptors.js:618:8)
    at InterceptingListener._callNext (C:\Users\rm\myProjects\Projects\evonet\node_modules\dash\node_modules\grpc\src\client_interceptors.js:574:12)
    at InterceptingListener.onReceiveStatus (C:\Users\rm\myProjects\Projects\evonet\node_modules\dash\node_modules\grpc\src\client_interceptors.js:618:8)
    at callback (C:\Users\rm\myProjects\Projects\evonet\node_modules\dash\node_modules\grpc\src\client_interceptors.js:847:24) {
  code: 3,
  metadata: Metadata {
    _internal_repr: {
      server: [Array],
      date: [Array],
      'content-length': [Array],
      errors: [Array]
    },
    flags: 0
  },
  details: 'Invalid state transition'
}
```

If i add the dpns arguments:
```
const clientOpts = {
  wallet: {
    mnemonic: 'velvet timber under input escape rich gauge final submit burst glow garage',
  },
  apps: {
    dpns: { "contractId" : "1FiBkhut4LFPMJqDWbZrxVeT6Mr6LsH3mTNTSSHJY2ape"}
  }
};
```

```
Something went wrong: TypeError: Cannot read property 'isDocumentDefined' of null
    at DocumentFactory.create (C:\Users\rm\myProjects\Projects\evonet\node_modules\dash\node_modules\@dashevo\dpp\lib\document\DocumentFactory.js:42:23)
    at DocumentFacade.create (C:\Users\rm\myProjects\Projects\evonet\node_modules\dash\node_modules\@dashevo\dpp\lib\document\DocumentFacade.js:42:25)
    at Platform.<anonymous> (C:\Users\rm\myProjects\Projects\evonet\node_modules\dash\build\src\SDK\Client\Platform\methods\documents\create.js:64:56)
    at step (C:\Users\rm\myProjects\Projects\evonet\node_modules\dash\build\src\SDK\Client\Platform\methods\documents\create.js:33:23)
    at Object.next (C:\Users\rm\myProjects\Projects\evonet\node_modules\dash\build\src\SDK\Client\Platform\methods\documents\create.js:14:53)
    at fulfilled (C:\Users\rm\myProjects\Projects\evonet\node_modules\dash\build\src\SDK\Client\Platform\methods\documents\create.js:5:58)
```

## Your Environment
* Version used: 3.14.1
* Environment name and version (e.g. Chrome 39, node.js 5.4): console using node 
* Operating System and version (desktop, server, or mobile): Windows
* Link to your project:

**Comment by jawid-h** [comment]
@readme55 Thank you for submitting an issue! Unfortunately we cannot seems to reproduce the first case. Could you, please, write the code you're trying to execute that is leading to `Something went wrong: Error: 3 INVALID_ARGUMENT: Invalid state transition`?

**Comment by jawid-h** [comment]
@readme55 In the second case you're having the wrong contract id, you may try to set it to `FiBkhut4LFPMJqDWbZrxVeT6Mr6LsH3mTNTSSHJY2ape`, it should work. We suppose to throw an error that is easier to understand, for sure.

By the way, here is the code that is working for me:

```const Dash = require('dash');

async function main() {
  const client = new Dash.Client({
    wallet: {
      mnemonic: 'velvet timber under input escape rich gauge final submit burst glow garage',
    },
  });

  const identity = await client.platform.identities.register()
  
  console.dir(identity);
  
  const result = await client.platform.names.register('youdomainnamehere.dash', identity);

  console.dir(result);
}

main().catch((e) => console.dir(e));```

**Comment by readme55** [comment]
@jawid-h thx for reply. Yeah i somehow mistyped the dpns id here, thx!

So for the first case, i just found whats wrong thanks to your code. So i have to add ".dash" to the name. Thats a breaking change I didnt know of.

```
const nameRegistration = await platform.names.register('mydapp', identity);
```
leads to the invalid state transition error

adding .dash to the name fixes that and i got a name registered now! 👍

**Comment by jawid-h** [comment]
Great, glad you've resolved your issue. In the future, if you'll get `Error: 3 INVALID_ARGUMENT: Invalid state transition` you may try to check the reason by exploring an error's metadata `JSON.parse(error.metadata.get('errors')[0])`. Yeah, that should be easier as well :sweat_smile:

**Comment by thephez** [comment]
@jawid-h Is there a reason the default `dash` parent domain was removed? Previously it was added by default if a non-domain name (i.e. just `thephez`) was provided.
