### ISSUE TITLE
Error creating Data-Contract with type Object

### ISSUE THREAD

**Issue by readme55** [dashevo/DashJS#49]
### Expected Behavior

no error when creating data-contract with property type object.

### Current Behavior

error:
```
{
  contract: DataContract {
    id: '94V37yGMYiCDU2BHPRmi2t3p2YdS6YQ4fdTQ8NECSyyP',
    ownerId: '14c3vc1qdsCgfPNVkxnZuJJyibAx4aQGsQPtUhkrStVt',
    schema: 'https://schema.dash.org/dpp-0-4-0/meta/data-contract',
    documents: {
      message: {
        properties: {
          identityid: { type: 'string' },
          header: { type: 'string' },
          body: { type: 'object' },
          plaintext: { type: 'string' }
        },
        additionalProperties: false
      }
    },
    definitions: {},
    entropy: 'yieNQ8BMNnEUYovT8Ebtas2c7NUpCNYmiT'
  }
}
Something went wrong: Error: 3 INVALID_ARGUMENT: State Transition is invalid
    at Object.exports.createStatusError (C:\Users\readme\myProjects\Projects\evonet\node_modules\grpc\src\common.js:91:15)
    at Object.onReceiveStatus (C:\Users\readme\myProjects\Projects\evonet\node_modules\grpc\src\client_interceptors.js:1209:28)
    at InterceptingListener._callNext (C:\Users\readme\myProjects\Projects\evonet\node_modules\grpc\src\client_interceptors.js:568:42)
    at InterceptingListener.onReceiveStatus (C:\Users\readme\myProjects\Projects\evonet\node_modules\grpc\src\client_interceptors.js:618:8)
    at InterceptingListener._callNext (C:\Users\readme\myProjects\Projects\evonet\node_modules\grpc\src\client_interceptors.js:574:12)
    at InterceptingListener.onReceiveStatus (C:\Users\readme\myProjects\Projects\evonet\node_modules\grpc\src\client_interceptors.js:618:8)
    at callback (C:\Users\readme\myProjects\Projects\evonet\node_modules\grpc\src\client_interceptors.js:847:24) {
  code: 3,
  metadata: Metadata {
    _internal_repr: {
      server: [Array],
      date: [Array],
      'content-length': [Array],
      errors: [Array]
    },
    flags: 0
  },
  details: 'State Transition is invalid'
}
```

### Context

submitting following contract:
```
    const contractDocuments = {
      message: {
        properties: {
          identityid: {
            type: "string"
          },
          header: {
            type: "string"
          },
          body: {
            type: "object"
          },
          plaintext: {
            type: "string"
          }
        },
        additionalProperties: false
      }
    };
```

### Steps to Reproduce & logs

heres my code:
```
const registerContract = async function () {
  try {
    await client.isReady();
    const platform = client.platform;
    const identity = await platform.identities.get('14c3vc1qdsCgfPNVkxnZuJJyibAx4aQGsQPtUhkrStVt');

    const contractDocuments = {
      message: {
        properties: {
          identityid: {
            type: "string"
          },
          header: {
            type: "string"
          },
          body: {
            type: "object"
          },
          plaintext: {
            type: "string"
          }
        },
        // indices: [
        //   {
        //     properties: [{ "header": "desc" }],
        //     unique: false
        //   }
        // ],
        additionalProperties: false
      }
    };
    const contract = await platform.contracts.create(contractDocuments, identity);
    console.dir({ contract }, { depth: 15 });

    // Sign and submit the data contract
    console.dir(await platform.contracts.broadcast(contract, identity));
  } catch (e) {
    console.error('Something went wrong:', e);
  } finally {
    client.disconnect();
  }
}
registerContract();
```

**Comment by Alex-Werner** [comment]
Hey @readme55, 
Do I guess it right that if you re-execute the same code it should be fine now ?

**Comment by thephez** [comment]
@readme55 One of your properties (`body`) is defined as `type: "object"`, but then does not define any properties for the object. This breaks JSON-Schema validation rules (not sure if that is the platform data contract-specific validation or just JSON-Schema in general).

**Comment by thephez** [comment]
@Alex-Werner Should we add that validation to contracts.broadcast before actually creating the ST? https://github.com/dashevo/DashJS/blob/master/src/SDK/Client/Platform/methods/contracts/broadcast.ts#L15

**Comment by Alex-Werner** [comment]
I think it will be on next DPP release that we will be able to uses it, I've forward that to @shumkov and @antouhou for them to be aware of the output we have here, but mid-term yes, we want to improve probably : 
- Comprehensibility of the errors (we know already where is the problem, but we had an issue communicating it on the errors)
- Local validation (before sending it to the node, but the node also tells us the issue, so that would be to offset that from node beforehand making the request)

**Comment by shumkov** [comment]
Actually, we just need to validate data before we send them in the SDK using DPP validate functions.

**Comment by thephez** [comment]
@readme55 I think this issue can be closed now?
